# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: Techcasts
tagline: 'A FSFTN initiative'
description: 'Techcasts will be a platform for FSFTN contributors to make technical videos and release them into the Free and Open knowledge domain.'
url:              http://fsftn.github.io/tech-casts/
baseurl:          http://fsftn.github.io/tech-casts/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/FSFTN/tech-casts
