# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tech Casts -- Blog -- FSFTN
tagline:          'Get to know about Tech Casts by FSFTN'
description:      'Tech Casts is an initiative by FSFTN to make tutorial videos about various languages, technologies and tools to distribute to the world as Free and Open knowledge. Stay excited and keep in touch to see further development!'
url:              http://fsftn.github.io/tech-casts/
baseurl:          http://fsftn.github.io/tech-casts/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/FSFTN/tech-casts
